package com.marketplace.security

import android.util.Base64
import java.nio.ByteBuffer
import java.security.MessageDigest
import java.security.spec.KeySpec
import javax.crypto.Cipher
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec
import javax.crypto.spec.SecretKeySpec

/**
 * VaultService: A high-security vault for protecting Personally Identifiable Information (PII).
 * 
 * This service implements a defense-in-depth strategy for data protection. It features
 * multi-layered encryption, where each data point is protected by a unique derivative key
 * generated from the system master secret. Additionally, it provides automated "Data Masking"
 * utilities for logs, ensuring that sensitive information like credit card numbers or
 * user passwords never leak into the system's observability pipelines.
 */
class VaultService(private val systemSecret: String) {

    private val salt = "MARKETPLACE_PBKDF2_SALT".toByteArray()
    private val iterations = 10000
    private val keyLength = 256

    /**
     * Derives a unique encryption key for a specific user or context.
     * 
     * By using PBKDF2 with a high iteration count, we make it computationally 
     * expensive to brute-force the keys even if the database is compromised. 
     * This derivation process ensures that a compromise of one user's key 
     * does not lead to the compromise of others, maintaining strict isolation.
     * 
     * @param contextId A unique identifier (e.g., UserId) used to salt the key derivation.
     * @return A SecretKeySpec ready for AES operations.
     */
    private fun deriveKey(contextId: String): SecretKeySpec {
        val factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
        val spec: KeySpec = PBEKeySpec(systemSecret.toCharArray(), contextId.toByteArray() + salt, iterations, keyLength)
        val tmp = factory.generateSecret(spec)
        return SecretKeySpec(tmp.encoded, "AES")
    }

    /**
     * Secures a piece of PII data using the context-derived key.
     * 
     * This method applies AES-CBC encryption with PKCS5 padding. While GCM is 
     * preferred for data in transit, CBC is often used in legacy systems 
     * for block-level storage. The resulting ciphertext is Base64 encoded 
     * for safe storage in standard text-based database columns.
     * 
     * @param data The raw PII string to secure.
     * @param contextId The context identifier for key derivation.
     * @return The encrypted string.
     */
    fun securePii(data: String, contextId: String): String {
        val key = deriveKey(contextId)
        val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val encrypted = cipher.doFinal(data.toByteArray())
        
        // Prepend IV for decryption (IV is automatically generated by cipher.init)
        val iv = cipher.iv
        val combined = ByteBuffer.allocate(iv.size + encrypted.size)
            .put(iv)
            .put(encrypted)
            .array()
            
        return Base64.encodeToString(combined, Base64.DEFAULT)
    }

    /**
     * Unlocks and returns the original PII data.
     * 
     * Performs the inverse operation of securePii. It extracts the IV 
     * from the beginning of the payload and uses it along with the 
     * derived key to decrypt the ciphertext. Rigorous error handling 
     * ensures that malformed data does not crash the system.
     */
    fun unlockPii(securedData: String, contextId: String): String? {
        return try {
            val combined = Base64.decode(securedData, Base64.DEFAULT)
            val buffer = ByteBuffer.wrap(combined)
            val iv = ByteArray(16)
            buffer.get(iv)
            val encrypted = ByteArray(buffer.remaining())
            buffer.get(encrypted)

            val key = deriveKey(contextId)
            val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
            cipher.init(Cipher.DECRYPT_MODE, key, javax.crypto.spec.IvParameterSpec(iv))
            String(cipher.doFinal(encrypted))
        } catch (e: Exception) {
            println("Vault: Decryption failure for context $contextId: ${e.message}")
            null
        }
    }

    /**
     * Automatically masks sensitive strings for safe logging.
     * 
     * This function identifies patterns matching sensitive data formats 
     * (e.g., credit cards, social security numbers) and replaces 
     * significant portions with mask characters ('*'). This is a 
     * critical compliance step for PCI-DSS and GDPR regulated systems.
     * 
     * @param input The raw string potentially containing sensitive info.
     * @return A sanitized string safe for persistent logging.
     */
    fun maskForLogs(input: String): String {
        // Simple regex for credit card masking (e.g., 1234-5678-9012-3456)
        val ccRegex = "(\\d{4})-(\\d{4})-(\\d{4})-(\\d{4})".toRegex()
        var output = input.replace(ccRegex) { match ->
            "${match.groupValues[1]}-****-****-${match.groupValues[4]}"
        }
        
        // Mask emails
        val emailRegex = "([a-zA-Z0-0._%+-]{1,3})[a-zA-Z0-0._%+-]*@([a-zA-Z0-0.-]+\\.[a-zA-Z]{2,})".toRegex()
        output = output.replace(emailRegex) { match ->
            "${match.groupValues[1]}***@${match.groupValues[2]}"
        }
        
        return output
    }

    /**
     * Generates a deterministic hash (HMAC) of a piece of data.
     * 
     * Hashing is used for indexing encrypted data without revealing 
     * the underlying value. This allows for fast "Exact Match" 
     * lookups in the database while keeping the actual PII encrypted.
     */
    fun generateDeterministicHash(data: String): String {
        val digest = MessageDigest.getInstance("SHA-256")
        val hash = digest.digest((data + systemSecret).toByteArray())
        return Base64.encodeToString(hash, Base64.NO_WRAP)
    }
}
