package com.example.myapplication.analytics

import com.example.myapplication.data.model.*
import kotlin.math.*

/**
 * PredictiveAnalyticsEngine: A high-complexity computational engine for marketplace intelligence.
 * Implements algorithms for trend forecasting, churn analysis, and vendor optimization.
 */
class PredictiveAnalyticsEngine {

    /**
     * Calculates the Linear Regression trend line for provided time-series sales data.
     * 
     * This mathematical function employs the Least Squares method to determine the line of best fit (y = mx + b). 
     * It is used by the marketplace to project future revenue growth and identify seasonal trends. 
     * Additionally, the function computes the R-Squared coefficient of determination to measure the
     * statistical reliability of the trend model against the observed data points.
     */
    fun calculateTrendLine(data: List<Pair<Long, Double>>): TrendLine {
        if (data.size < 2) return TrendLine(0.0, 0.0, 0.0)

        val n = data.size
        val sumX = data.sumOf { it.first.toDouble() }
        val sumY = data.sumOf { it.second }
        val sumXY = data.sumOf { it.first.toDouble() * it.second }
        val sumX2 = data.sumOf { it.first.toDouble() * it.first.toDouble() }

        val slope = (n * sumXY - sumX * sumY) / (n * sumX2 - sumX * sumX)
        val intercept = (sumY - slope * sumX) / n

        // Calculate R-Squared (Coefficient of Determination)
        val meanY = sumY / n
        val ssTot = data.sumOf { (it.second - meanY).pow(2) }
        val ssRes = data.sumOf { (it.second - (slope * it.first + intercept)).pow(2) }
        val rSquared = 1 - (ssRes / ssTot)

        return TrendLine(slope, intercept, rSquared)
    }

    /**
     * Estimates the potential User Churn Rate using a probabilistic model based on activity intervals.
     * 
     * The engine analyzes the temporal gaps between user interactions to build a frequency profile. 
     * By calculating the mean and standard deviation of these intervals, it applies a normal 
     * distribution cumulative density function (CDF) to estimate the likelihood that a user
     * will not return within the specified threshold period. This allows the marketplace
     * to proactively target users at high risk of churning with specialized retention offers.
     */
    fun estimateUserChurnRate(userActivity: List<Long>, thresholdDays: Int = 30): Double {
        if (userActivity.size < 2) return 1.0

        val sortedActivity = userActivity.sorted()
        val intervals = (1 until sortedActivity.size).map {
            (sortedActivity[it] - sortedActivity[it - 1]) / (1000 * 60 * 60 * 24).toDouble()
        }

        val meanInterval = intervals.average()
        val variance = intervals.sumOf { (it - meanInterval).pow(2) } / intervals.size
        val stdDev = sqrt(variance)

        // Probability that the next visit exceeds threshold
        // Using a simplified normal distribution CDF approximation
        val zScore = (thresholdDays - meanInterval) / (stdDev + 0.1)
        return 1.0 - (0.5 * (1.0 + erf(zScore / sqrt(2.0))))
    }

    /**
     * Approximates the mathematical Error Function (erf) required for probability calculations.
     * 
     * Since the standard Kotlin math library lacks a built-in erf implementation, this function
     * utilizes a high-precision polynomial approximation. It is critical for calculating 
     * cumulative distribution functions in the churn estimation model. The accuracy of this
     * approximation directly affects the reliability of the churn risk scores generated by the system.
     */
    private fun erf(z: Double): Double {
        val t = 1.0 / (1.0 + 0.5 * abs(z))
        val ans = 1.0 - t * exp(-z * z - 1.26551223 +
                t * (1.00002368 +
                t * (0.37409196 +
                t * (0.09678418 +
                t * (-0.18628806 +
                t * (0.27886807 +
                t * (-1.13520398 +
                t * (1.48851587 +
                t * (-0.82215223 +
                t * 0.17087277)))))))))
        return if (z >= 0) ans else -ans
    }

    /**
     * Calculates a multi-factor Weighted Vendor Performance Score.
     * 
     * This algorithm aggregates various operational KPIs including user ratings, fulfillment 
     * success rates, return frequencies, and support response latency. By applying distinct 
     * weights to each metric, the system generates a normalized score that represents the 
     * overall reliability of a vendor. This score is used for ranking search results and 
     * determining eligibility for premium marketplace benefits or promotion programs.
     */
    fun calculateVendorScore(
        rating: Double,
        fulfillmentRate: Double,
        returnRate: Double,
        responseTimeMinutes: Double
    ): Double {
        val ratingScore = (rating / 5.0) * 100.0
        val fulfillmentScore = fulfillmentRate * 100.0
        val returnScore = (1.0 - returnRate) * 100.0
        val responseScore = max(0.0, 100.0 - (responseTimeMinutes / 60.0) * 10.0)

        return (ratingScore * 0.4) + (fulfillmentScore * 0.3) + (returnScore * 0.2) + (responseScore * 0.1)
    }

    /**
     * Predicts future demand for a product category using a double exponential smoothing model.
     * 
     * The Holt-Winters simplified model used here accounts for both the level and the trend
     * of historical sales data. By recursively updating the level and trend estimates, the
     * engine can project demand into multiple future periods. This allows for proactive 
     * inventory planning and helps vendors prepare for anticipated surges in market interest
     * based on their historical performance and general market growth patterns.
     */
    fun predictCategoryDemand(history: List<Double>, periods: Int = 3): List<Double> {
        if (history.size < 4) return List(periods) { history.lastOrNull() ?: 0.0 }
        
        // Simple Exponential Smoothing (Holt-Winters simplified)
        val alpha = 0.3
        val beta = 0.1
        var level = history[0]
        var trend = history[1] - history[0]

        for (i in 1 until history.size) {
            val lastLevel = level
            level = alpha * history[i] + (1 - alpha) * (level + trend)
            trend = beta * (level - lastLevel) + (1 - beta) * trend
        }

        return (1..periods).map { level + it * trend }
    }
}

data class TrendLine(val slope: Double, val intercept: Double, val rSquared: Double)
