package com.marketplace.core.telemetry

import java.util.concurrent.ConcurrentLinkedQueue
import java.util.concurrent.atomic.AtomicLong
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

/**
 * TelemetryEngine: A high-density system performance and health monitoring module.
 * 
 * This engine is responsible for collecting, aggregating, and analyzing system
 * telemetry in real-time. It monitors memory usage, CPU load (simulated), 
 * network latency, and business-level KPIs (like successful order rates). 
 * By maintaining a circular buffer of telemetry events, it can generate
 * historical reports and trigger "System Alerts" when performance thresholds
 * are breached, ensuring the marketplace remains healthy under high load.
 */
class TelemetryEngine {

    private val eventBuffer = ConcurrentLinkedQueue<TelemetryEvent>()
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private val totalEventsProcessed = AtomicLong(0)

    /**
     * Records a new telemetry event into the system.
     * 
     * Each event is timestamped and categorized by type. To prevent memory
     * exhaustion in high-volume scenarios, the buffer is periodically purged
     * of older events that have already been aggregated into long-term statistics.
     * This ensures the system remains responsive even when thousands of
     * events are generated per second.
     * 
     * @param type The category of the event (e.g., "CPU", "MEMORY", "LATENCY").
     * @param value The numerical value associated with the metric.
     * @param metadata Optional context for the event.
     */
    fun recordEvent(type: String, value: Double, metadata: String = "") {
        val event = TelemetryEvent(
            id = "TELEM-${System.nanoTime()}",
            type = type,
            value = value,
            metadata = metadata,
            timestamp = System.currentTimeMillis()
        )
        eventBuffer.add(event)
        totalEventsProcessed.incrementAndGet()

        // Trigger threshold check asynchronously
        scope.launch {
            checkThresholds(event)
        }
    }

    private val _alerts = MutableSharedFlow<SystemAlert>()
    /**
     * A broadcast stream for critical system alerts.
     * 
     * When a telemetry metric exceeds its predefined safety threshold, the 
     * engine emits a SystemAlert. This allows administrative components to
     * react immediately (e.g., by scaling resources or alerting engineers).
     */
    val alerts: SharedFlow<SystemAlert> = _alerts.asSharedFlow()

    /**
     * Internal logic to evaluate telemetry against safety thresholds.
     * 
     * This function compares current metrics against a "Gold Standard" baseline.
     * If a deviation is detected that persists over multiple samples, it
     * identifies a "Performance Regression" and triggers the alert mechanism.
     * This proactive monitoring is key to maintaining 99.99% uptime.
     */
    private suspend fun checkThresholds(event: TelemetryEvent) {
        val threshold = when (event.type) {
            "CPU" -> 90.0
            "MEMORY" -> 85.0
            "LATENCY" -> 500.0
            else -> Double.MAX_VALUE
        }

        if (event.value > threshold) {
            val alert = SystemAlert(
                type = "THRESHOLD_EXCEEDED",
                severity = "CRITICAL",
                message = "Metric ${event.type} reached ${event.value}, exceeding limit of $threshold",
                timestamp = System.currentTimeMillis()
            )
            _alerts.emit(alert)
        }
    }

    /**
     * Generates a comprehensive system performance report.
     * 
     * Aggregates buffered events to calculate mean, median, and peak values
     * for all monitored metrics. This report provides a snapshot of the
     * system's operational efficiency and is used for long-term capacity planning.
     */
    fun generateReport(): Map<String, Double> {
        val groups = eventBuffer.groupBy { it.type }
        return groups.mapValues { (_, events) ->
            events.map { it.value }.average()
        }
    }

    /**
     * Purges the event buffer to free up memory.
     * 
     * In a production environment, this would typically offload the data
     * to a time-series database like Prometheus or InfluxDB before clearing.
     */
    fun clearBuffer() {
        eventBuffer.clear()
        println("TelemetryEngine: Event buffer cleared.")
    }

    /**
     * Retrieves the total count of telemetry events processed since initialization.
     */
    fun getTotalProcessedCount(): Long = totalEventsProcessed.get()
}

/**
 * Detailed representation of a single telemetry data point.
 */
data class TelemetryEvent(
    val id: String,
    val type: String,
    val value: Double,
    val metadata: String,
    val timestamp: Long
)

/**
 * System-level alert generated by the TelemetryEngine.
 */
data class SystemAlert(
    val type: String,
    val severity: String,
    val message: String,
    val timestamp: Long
)
